import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from 'file:///C:/Users/Ramos/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs';
import {finalizePresentation} from 'file:///C:/Users/Ramos/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='C:/Users/Ramos/Documents/FocusSync';
const skill='C:/Users/Ramos/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const p=Presentation.create({slideSize:{width:1280,height:720}});
const slides=[
{title:'FocusSync',label:'01  EL PROBLEMA',time:'0:00–0:35',big:'¿Cuánto de tu tiempo de estudio\nes realmente tiempo de enfoque?',body:'Una sesión puede empezar sin un plan claro\ny terminar entre interrupciones del teléfono.',notes:'Pensemos en una situación cotidiana: tenemos un examen, nos sentamos a estudiar y dejamos el teléfono a un lado. Poco después lo levantamos, perdemos el hilo y volvemos a empezar. Al terminar, sabemos cuánto tiempo pasó, pero no cuánto aprovechamos. FocusSync parte de ese problema: organizar el estudio y reconocer las interrupciones. Está dirigido a estudiantes que necesitan una rutina más clara y una forma de revisar su actividad.'},
{title:'El valor de FocusSync',label:'02  LA IDEA CENTRAL',time:'0:35–1:15',big:'Un plan de estudio conectado\ncon la sesión y su historial',body:'La IA propone bloques de trabajo.\nEl modo enfoque acompaña su ejecución.\nEl historial permite revisar lo que ocurrió.',notes:'El valor de FocusSync consiste en conectar la planificación con lo que realmente ocurre durante una sesión. El estudiante puede pedir ayuda para organizar un tema, elegir un bloque y comenzar a trabajar. Después puede consultar su historial. Así, la propuesta reúne acciones que suelen quedar separadas: decidir qué estudiar y revisar cómo se estudió. No afirmamos que la aplicación garantice mejores calificaciones. Buscamos ofrecer una herramienta para tomar decisiones sobre la propia rutina a partir de la actividad registrada.'},
{title:'Una sesión de estudio',label:'03  QUÉ HACE LA SOLUCIÓN',time:'1:15–2:05',big:'“Tengo 55 minutos para\nrepasar bases de datos”',body:'25 min de teoría     5 min de descanso     25 min de práctica\n\nEl estudiante elige un bloque, coloca el teléfono boca abajo\ny consulta el registro al terminar.',notes:'Veamos un ejemplo ilustrativo. Un estudiante escribe: tengo cincuenta y cinco minutos para repasar bases de datos. El plan puede dividirse en veinticinco minutos de teoría, cinco de descanso y veinticinco de práctica. El estudiante revisa los pasos y abre un bloque en el modo enfoque. En un teléfono compatible, el cronómetro espera a que el dispositivo esté boca abajo. Si se levanta durante la sesión, la aplicación detecta la interrupción y pausa el enfoque. Luego el estudiante puede retomar el bloque y consultar la actividad. Este ejemplo describe el recorrido. El historial de prueba que preparamos contiene datos simulados y no representa una evaluación con usuarios.'},
{title:'Beneficios para el estudiante',label:'04  BENEFICIO PARA EL USUARIO',time:'2:05–2:45',big:'Una rutina más fácil de revisar',body:'Claridad para empezar: un tema dividido en bloques.\n\nConciencia de las interrupciones: eventos registrados.\n\nSeguimiento personal: sesiones, minutos y meta diaria.',notes:'Los beneficios esperados se relacionan con decisiones concretas. Primero, dividir un tema en bloques ayuda a saber por dónde comenzar. Segundo, registrar interrupciones permite reconocer cuándo se rompe la sesión, en lugar de depender solamente de la memoria. Tercero, el historial y la meta diaria ofrecen una referencia para revisar la constancia. Esto puede servir como apoyo al aprendizaje autónomo. Todavía necesitamos observar el uso real para medir esos beneficios. Por eso distinguimos entre lo que la aplicación permite hacer y el impacto que esperamos comprobar con estudiantes.'},
{title:'La tecnología que lo sostiene',label:'05  RESPALDO TÉCNICO',time:'2:45–3:30',big:'La app guarda el contexto\nde cada sesión',body:'Expo y React Native: aplicación móvil y sensores.\nSupabase: acceso, base de datos y reglas por usuario.\nGemini: generación de planes mediante una función del servidor.',notes:'La implementación utiliza Expo y React Native para la aplicación móvil y el acceso a los sensores. Supabase gestiona la autenticación y la base de datos. Cada plan pertenece a un usuario, los bloques pertenecen a un plan y las sesiones registran su ejecución. Las reglas de acceso buscan que cada persona consulte sus propios datos. Para generar planes, la app llama a una función del servidor que utiliza Gemini. La clave de ese servicio permanece en el servidor. Esta estructura permite relacionar la solicitud de estudio con el plan y con las sesiones guardadas, en lugar de mostrar información aislada.'},
{title:'Un reto concreto del proyecto',label:'06  EVIDENCIA DE PARTICIPACIÓN',time:'3:30–4:25',big:'Registrar una interrupción\nsin repetir el mismo evento',body:'Reto: los sensores notifican cambios continuamente.\nDecisión en el código: registrar una vez por interrupción.\nComprobación propuesta: levantar, revisar y reanudar.',notes:'Un reto concreto que podemos explicar está en el modo enfoque. Los sensores notifican cambios continuamente. Si cada lectura generara una distracción, una sola acción podría producir varios registros. El código utiliza una bandera para recordar que esa interrupción ya fue atendida. Cuando comienza o se retoma el enfoque, restablece ese control. Una comprobación útil consiste en iniciar un bloque, levantar el teléfono y revisar que aparezca un solo evento para esa interrupción. Después se reanuda y se repite la acción. Este ejemplo muestra una decisión verificable en el proyecto. Antes de exponer, quien desarrolló esta parte debe explicar su contribución personal y el resultado que realmente observó.',extra:'Decisión verificable en el código. La autoría individual debe confirmarla el equipo.'},
{title:'El siguiente paso',label:'07  CIERRE Y LLAMADO A LA ACCIÓN',time:'4:25–5:00',big:'Probar una sesión completa\ncon estudiantes',body:'Pedir un plan, completar un bloque y revisar el historial.\n\nObservar qué ayuda, qué confunde y qué debemos mejorar.',notes:'FocusSync propone una forma de organizar el estudio y revisar cómo se lleva a cabo. Su valor está en unir el plan con la actividad del estudiante. El siguiente paso que proponemos es realizar una prueba completa con estudiantes: pedir un plan, ejecutar un bloque y revisar el historial. Queremos escuchar si el recorrido resulta claro y si la información les ayuda a ajustar su rutina. Con esas observaciones podremos priorizar mejoras y evaluar el aporte real de la aplicación. Gracias.'}
];
function text(s,t,x,y,w,h,size,color='#183153',bold=false){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:'Arial',fontSize:size,color,bold,autoFit:'none'};return a;}
for(let i=0;i<slides.length;i++){const d=slides[i],s=p.slides.add();const dark=i===0||i===6;s.background.fill=dark?'#142C48':'#F7F8FA';const fg=dark?'#FFFFFF':'#183153';text(s,d.label,72,40,1050,35,19,dark?'#80DCCB':'#327B70',true);text(s,d.title,72,95,1136,75,48,fg,true);text(s,d.big,72,215,1136,145,i===0?45:43,fg,true);text(s,d.body,72,395,1136,190,26,dark?'#DAE4EF':'#40536B');if(d.extra)text(s,d.extra,72,604,1136,30,18,'#586A7F');text(s,`${i+1} / 7`,1130,665,80,25,16,dark?'#DAE4EF':'#586A7F');s.speakerNotes.textFrame.setText(`TIEMPO: ${d.time}\n\n${d.notes}\n\nFuentes: Plantilla para crear presentaicon de proyectos.pdf, apartados 1 a 7. Repositorio FocusSync/README.md, FocusSync/features/focus/screens/FocusScreen.tsx, FocusSync/supabase/migrations/202608260001_initial_schema.sql. Funcionalidades descritas a partir del código, sin verificación de despliegue.`);}
const candidate=root+'/.presentation-build/candidate.pptx';
await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(root+`/.presentation-build/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
await fs.writeFile(root+'/output/presentaciones/Guion_FocusSync_5_minutos.md','# FocusSync: guion de cinco minutos\n\nDuración objetivo: 5:00. Los tiempos incluyen pausas y cambios de diapositiva. Ensaya con cronómetro para ajustar tu ritmo.\n\nLa sección 6 presenta una decisión real del código. Confirma quién la desarrolló antes de atribuirla a una persona. No se proporcionaron nombres de integrantes ni materia.\n\n'+slides.map((s,i)=>`## ${i+1}. ${s.title} (${s.time})\n\n${s.notes}`).join('\n\n'));
console.log(await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:root+'/output/presentaciones/FocusSync_5_minutos.pptx',pythonExecutable:'C:/Users/Ramos/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'design',families:['Arial']},verifyArtifactToolImport:true,receiptPath:root+'/.presentation-build/validation.json'}));

